// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPedidos.Orm.Core;

#nullable disable

namespace SistemaPedidos.API.Migrations
{
    [DbContext(typeof(SistemaPedidosContext))]
    [Migration("20240128130305_TipoUsuario")]
    partial class TipoUsuario
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.AdesaoEmpresa.Adesao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Adesao");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdesaoClienteId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("EhPlanoMensal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdAdesao")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdFormaPagamento")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdPlano")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdesaoClienteId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdStatusPedido")
                        .HasColumnType("char(36)");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Pedidos.PedidoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("PedidoProduto");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Pedidos.StatusPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdAdesao")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("StatusPedido");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdAdesao")
                        .HasColumnType("char(36)");

                    b.Property<double>("Preco")
                        .HasColumnType("double");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Sistema.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Modulo");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Sistema.Rotina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RotaUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Rotina");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdesaoUsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdAdesao")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("IdAspnetUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdesaoUsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Clientes.Cliente", b =>
                {
                    b.HasOne("SistemaPedidos.Domain.Entities.AdesaoEmpresa.Adesao", "AdesaoCliente")
                        .WithMany()
                        .HasForeignKey("AdesaoClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdesaoCliente");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Sistema.Rotina", b =>
                {
                    b.HasOne("SistemaPedidos.Domain.Entities.Sistema.Modulo", "Modulo")
                        .WithMany("Rotinas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.HasOne("SistemaPedidos.Domain.Entities.AdesaoEmpresa.Adesao", "AdesaoUsuario")
                        .WithMany()
                        .HasForeignKey("AdesaoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdesaoUsuario");
                });

            modelBuilder.Entity("SistemaPedidos.Domain.Entities.Sistema.Modulo", b =>
                {
                    b.Navigation("Rotinas");
                });
#pragma warning restore 612, 618
        }
    }
}
